spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/test
        username: root
    sql:
        init:
            password: ''
            schema-locations: classpath*:schema-all.sql
            username: root
