
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
        username: root
        password: root
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: create-drop
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
    level:
        root: trace
        org:
            apache:
                tomcat: info
        sun:
            rmi: info


